Repository likelion-onetool/backend, pull requests merged in 2024-09, with the labels that each got.

#50 [TIC-92] 카테고리 Controller와 Service 리팩터링
  server/src/main/java/com/onetool/server/DataLoader.java
  server/src/main/java/com/onetool/server/blueprint/controller/SearchController.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java
Labels: 🛠 fix, ♻️ refactor

#53 🎟️ [TIC-95] feat : 내 문의사항 조회 기능 추가
  server/src/main/java/com/onetool/server/cart/controller/CartController.java
  server/src/main/java/com/onetool/server/cart/dto/CartRequest.java
  server/src/main/java/com/onetool/server/member/controller/MemberController.java
  server/src/main/java/com/onetool/server/member/repository/MemberRepository.java
  server/src/main/java/com/onetool/server/member/service/MemberService.java
  server/src/main/java/com/onetool/server/qna/controller/QnaBoardController.java
  server/src/main/java/com/onetool/server/qna/controller/QnaReplyController.java
  server/src/main/java/com/onetool/server/qna/dto/response/QnaBoardResponse.java
  server/src/main/java/com/onetool/server/qna/dto/response/QnaReplyResponse.java
  server/src/main/java/com/onetool/server/qna/service/QnaBoardServiceImpl.java
Labels: ✨ feat, ♻️ refactor

#56 [TIC-93] Refresh Token 구현 및 Redis 관련 수정
  server/build.gradle
  server/src/main/java/com/onetool/server/global/auth/AuthService.java
  server/src/main/java/com/onetool/server/global/auth/AuthorizationProvider.java
  server/src/main/java/com/onetool/server/global/auth/CustomAuthenticationEntryPoint.java
  server/src/main/java/com/onetool/server/global/auth/filter/JwtAuthFilter.java
  server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java
  server/src/main/java/com/onetool/server/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/onetool/server/global/auth/login/service/CustomUserDetailsService.java
  server/src/main/java/com/onetool/server/global/config/RedisConfig.java
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
  server/src/main/java/com/onetool/server/global/exception/InvalidTokenException.java
  server/src/main/java/com/onetool/server/global/exception/WebErrorController.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/main/java/com/onetool/server/global/redis/config/RedisConfig.java
  server/src/main/java/com/onetool/server/global/redis/controller/TokenController.java
  server/src/main/java/com/onetool/server/global/redis/domain/Token.java
  server/src/main/java/com/onetool/server/global/redis/domain/dto/RefreshTokenResponse.java
  server/src/main/java/com/onetool/server/global/redis/repository/TokenRepository.java
  server/src/main/java/com/onetool/server/global/redis/service/MailRedisService.java
  server/src/main/java/com/onetool/server/global/redis/service/TokenRedisService.java
  server/src/main/java/com/onetool/server/member/controller/MemberController.java
  server/src/main/java/com/onetool/server/member/dto/MemberLoginResponse.java
  server/src/main/java/com/onetool/server/member/service/MemberService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
  server/src/test/java/com/onetool/server/redis/RedisCrudTest.java
Labels: 🛠 fix, ✨ feat

#62 [TIC-98] 검수가 필요한 도면 조회, 승인
  server/src/main/java/com/onetool/server/TestDataLoader.java
  server/src/main/java/com/onetool/server/blueprint/Blueprint.java
  server/src/main/java/com/onetool/server/blueprint/InspectionStatus.java
  server/src/main/java/com/onetool/server/blueprint/controller/BlueprintInspectionController.java
  server/src/main/java/com/onetool/server/blueprint/repository/BlueprintRepository.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintInspectionService.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintInspectionTest.java
  server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
Labels: ✨ feat

#63 [main 합병] feat/inspection-> main
  server/src/main/java/com/onetool/server/TestDataLoader.java
  server/src/main/java/com/onetool/server/blueprint/Blueprint.java
  server/src/main/java/com/onetool/server/blueprint/InspectionStatus.java
  server/src/main/java/com/onetool/server/blueprint/controller/BlueprintInspectionController.java
  server/src/main/java/com/onetool/server/blueprint/repository/BlueprintRepository.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintInspectionService.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintInspectionTest.java
  server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
Labels: 👍 Merge

#65 [TIC-101,102] feat: 자정마다 검수가 완료된 도면 새로고침 구현/ 검수 완료된 도면만 불러오도록 수정
  server/src/main/java/com/onetool/server/ServerApplication.java
  server/src/main/java/com/onetool/server/blueprint/controller/BlueprintController.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintInspectionService.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintRefreshService.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java
  server/src/main/java/com/onetool/server/global/exception/BlueprintNotApprovedException.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
Labels: ✨ feat

#67 🎟️ [TIC-100] 도면, 도면 상세 페이지 이미지 S3에 저장
  server/build.gradle
  server/src/main/java/com/onetool/server/blueprint/controller/BlueprintUploadController.java
  server/src/main/java/com/onetool/server/blueprint/dto/BlueprintUploadRequest.java
  server/src/main/java/com/onetool/server/blueprint/dto/BlueprintUploadResponse.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintS3UploadService.java
  server/src/main/java/com/onetool/server/global/config/S3Config.java
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
  server/src/main/java/com/onetool/server/global/exception/WebErrorController.java
  server/src/main/java/com/onetool/server/global/exception/codes/BaseCode.java
  server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
Labels: ✨ feat
