Repository likelion-onetool/backend, pull requests merged in 2024-11, with the labels that each got.

#77 [feat/blueprint 합병] feat/blueprint -> main
  .idea/onetool_backend.iml
  .idea/vcs.xml
  server/src/main/java/com/onetool/server/ServerApplication.java
  server/src/main/java/com/onetool/server/blueprint/controller/BlueprintController.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintInspectionService.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintRefreshService.java
  server/src/main/java/com/onetool/server/blueprint/service/BlueprintService.java
  server/src/main/java/com/onetool/server/global/exception/BlueprintNotApprovedException.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
Labels: 👍 Merge

#79 fix(redis): RedisTemplate 빈 충돌 문제
  server/src/main/java/com/onetool/server/global/redis/service/MailRedisService.java
  server/src/main/java/com/onetool/server/global/redis/service/TokenRedisService.java
  server/src/main/resources/application.properties
Labels: 🚨 hotfix

#84 [#83] test(member):회원 삭제 로직 오류 수정
  server/src/test/java/com/onetool/server/member/MemberServiceTest.java
Labels: ✅ test

#85 [#75] feat(deploy): CI/CD & compose 파일 생성
  .github/workflows/dev_deploy.yml
  compose.yml
  server/build.gradle
  server/src/main/java/com/onetool/server/DataLoader.java
  server/src/main/java/com/onetool/server/TestDataLoader.java
  server/src/main/java/com/onetool/server/global/auth/jwt/JwtUtil.java
  server/src/main/java/com/onetool/server/global/exception/ApiResponse.java
  server/src/main/java/com/onetool/server/member/dto/MemberUpdateRequest.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
  server/src/test/java/com/onetool/server/member/MemberServiceTest.java
Labels: 🗺 deploy

#89 chore: Actuator 라이브러리 추가
  server/build.gradle
Labels: 🗺 deploy

#91 fix(redis): RedisConfig 비밀번호 설정
  server/src/main/java/com/onetool/server/global/redis/config/RedisConfig.java
Labels: 🗺 deploy

#92 fix: DataLoader 프로파일 변경
  server/src/main/java/com/onetool/server/DataLoader.java
Labels: 🗺 deploy

#100 fix(security): PreFlight 요청 허가
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
Labels: 🚨 hotfix, 🛠 fix

#101 fix(security): anyRequest 후 requestMatchers 설정 문제
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
Labels: 🚨 hotfix
