Repository likelion-onetool/backend, pull requests merged in 2025-03, with the labels that each got.

#203 refactor(qna/cart/blueprint/order): 예외 리팩터링 및 적용
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintInspectionService.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
  server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java
  server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java
  server/src/main/java/com/onetool/server/api/cart/service/CartService.java
  server/src/main/java/com/onetool/server/api/order/service/OrderService.java
  server/src/main/java/com/onetool/server/api/qna/QnaBoard.java
  server/src/main/java/com/onetool/server/api/qna/QnaReply.java
  server/src/main/java/com/onetool/server/api/qna/service/QnaBoardService.java
  server/src/main/java/com/onetool/server/api/qna/service/QnaReplyService.java
  server/src/main/java/com/onetool/server/global/generator/RandomGenerator.java
  server/src/main/java/com/onetool/server/global/new_exception/exception/error/BlueprintErrorCode.java
  server/src/main/java/com/onetool/server/global/new_exception/exception/error/CartErrorCode.java
  server/src/main/java/com/onetool/server/global/new_exception/exception/error/OrderErrorCode.java
  server/src/main/java/com/onetool/server/global/new_exception/exception/error/QnaErrorCode.java
Labels: ♻️ refactor

#204 feat(swagger-ui) : swagger-ui 기능 구현
  server/build.gradle
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
  server/src/main/java/com/onetool/server/global/config/SwaggerConfig.java
Labels: ♻️ refactor

#208 refactor(filter): 필터 검사시 Member 쿼리자체가 2번 조회되는 문제와 N+1 문제가 발생 해결
  server/src/main/java/com/onetool/server/api/cart/Cart.java
  server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java
  server/src/main/java/com/onetool/server/global/auth/filter/JwtAuthFilter.java
  server/src/main/java/com/onetool/server/global/auth/login/service/CustomUserDetailsService.java
Labels: ♻️ refactor

#209 test(member): Fake Repository 기반 테스트 코드
  server/src/main/java/com/onetool/server/api/blueprint/business/BlueprintSearchBusiness.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
  server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java
  server/src/main/java/com/onetool/server/api/member/business/MemberBusiness.java
  server/src/main/java/com/onetool/server/api/member/business/MemberEmailBusiness.java
  server/src/main/java/com/onetool/server/api/member/business/MemberLoginBusiness.java
  server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java
  server/src/main/java/com/onetool/server/api/member/service/MemberService.java
  server/src/main/java/com/onetool/server/api/order/business/OrderBusiness.java
  server/src/main/java/com/onetool/server/api/qna/business/QnaBoardBusiness.java
  server/src/main/java/com/onetool/server/api/qna/business/QnaReplyBusiness.java
  server/src/main/java/com/onetool/server/data/TestDataLoader.java
  server/src/test/java/com/onetool/server/api/member/business/MemberBusinessTest.java
  server/src/test/java/com/onetool/server/api/member/fake/FakeMemberRepository.java
  server/src/test/java/com/onetool/server/api/payments/service/DepositServiceTest.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
  server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
Labels: ♻️ refactor, ✅ test

#211 test(member): Mockito를 이용한 controller - business - service 테스트 작성
  server/build.gradle
  server/src/main/java/com/onetool/server/api/member/dto/BlueprintDownloadResponse.java
  server/src/main/java/com/onetool/server/api/qna/repository/QnaBoardRepository.java
  server/src/main/resources/application-local.properties
  server/src/test/java/com/onetool/server/api/helper/MockBeanInjection.java
  server/src/test/java/com/onetool/server/api/member/business/MemberBusinessTest.java
  server/src/test/java/com/onetool/server/api/member/controller/MemberControllerTest.java
  server/src/test/java/com/onetool/server/api/member/fake/FakeMemberRepository.java
  server/src/test/java/com/onetool/server/api/member/fixture/MemberFixture.java
  server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetails.java
  server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetailsSecurityContextFactory.java
  server/src/test/java/com/onetool/server/api/member/service/MemberServiceTest.java
Labels: ♻️ refactor, ✅ test

#213 test(Qna): Mockito를 이용한 controller - business - service 테스트 작성
  server/build.gradle
  server/src/main/java/com/onetool/server/api/qna/QnaBoard.java
  server/src/main/java/com/onetool/server/api/qna/business/QnaBoardBusiness.java
  server/src/main/java/com/onetool/server/api/qna/business/QnaReplyBusiness.java
  server/src/main/java/com/onetool/server/api/qna/controller/QnaBoardController.java
  server/src/main/java/com/onetool/server/api/qna/controller/QnaReplyController.java
  server/src/main/java/com/onetool/server/api/qna/service/QnaBoardService.java
  server/src/main/java/com/onetool/server/api/qna/service/QnaReplyService.java
  server/src/main/java/com/onetool/server/global/entity/BaseEntity.java
  server/src/main/java/com/onetool/server/global/new_exception/exception/ApiException.java
  server/src/test/java/com/onetool/server/api/member/fixture/WithMockPrincipalDetailsSecurityContextFactory.java
  server/src/test/java/com/onetool/server/api/payments/service/DepositServiceTest.java
  server/src/test/java/com/onetool/server/api/qna/business/QnaBoardBusinessTest.java
  server/src/test/java/com/onetool/server/api/qna/business/QnaReplyBusinessTest.java
  server/src/test/java/com/onetool/server/api/qna/controller/QnaBoardControllerTest.java
  server/src/test/java/com/onetool/server/api/qna/controller/QnaReplyControllerTest.java
  server/src/test/java/com/onetool/server/api/qna/service/QnaBoardServiceTest.java
  server/src/test/java/com/onetool/server/api/qna/service/QnaReplyServiceTest.java
  server/src/test/java/com/onetool/server/fixture/MemberFixture.java
  server/src/test/java/com/onetool/server/fixture/QnaBoardFixture.java
  server/src/test/java/com/onetool/server/fixture/QnaReplyFixture.java
Labels: ✅ test

#216 feat(Orders): orders N+1문제 해결 2010 쿼리 -> 13개 쿼리 => 캐시 적용
  server/build.gradle
  server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
  server/src/main/java/com/onetool/server/api/order/Orders.java
  server/src/main/java/com/onetool/server/api/order/business/OrderBusiness.java
  server/src/main/java/com/onetool/server/api/order/controller/OrderController.java
  server/src/main/java/com/onetool/server/api/order/dto/response/MyPageOrderResponse.java
  server/src/main/java/com/onetool/server/api/order/repository/OrderRepository.java
  server/src/main/java/com/onetool/server/api/order/service/OrderService.java
  server/src/main/java/com/onetool/server/global/entity/BaseEntity.java
  server/src/main/java/com/onetool/server/global/redis/config/RedisCacheConfig.java
Labels: ✨ feat

#214 test(Cart) Cart 테스트 코드 작성
  server/src/main/java/com/onetool/server/api/blueprint/Blueprint.java
  server/src/main/java/com/onetool/server/api/cart/Cart.java
  server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java
  server/src/main/java/com/onetool/server/api/cart/business/CartBusiness.java
  server/src/main/java/com/onetool/server/api/cart/controller/CartController.java
  server/src/main/java/com/onetool/server/api/cart/dto/request/AddBlueprintToCartRequest.java
  server/src/main/java/com/onetool/server/api/cart/dto/response/CartItemResponse.java
  server/src/main/java/com/onetool/server/api/cart/dto/response/CartItemsResponse.java
  server/src/main/java/com/onetool/server/api/cart/service/CartService.java
  server/src/test/java/com/onetool/server/api/cart/business/CartBusinessTest.java
  server/src/test/java/com/onetool/server/api/cart/controller/CartControllerTest.java
  server/src/test/java/com/onetool/server/api/cart/fixture/CartFixture.java
  server/src/test/java/com/onetool/server/api/cart/service/CartServiceTest.java
  server/src/test/resources/application-test.yml
  server/src/test/resources/application.yml
Labels: ♻️ refactor, ✅ test

#218 refactor(member): 역방향 레이어드 아키텍처 수정
  server/src/main/java/com/onetool/server/api/counting/ServiceCountingService.java
  server/src/main/java/com/onetool/server/api/member/business/MemberBusiness.java
  server/src/main/java/com/onetool/server/api/member/business/MemberEmailBusiness.java
  server/src/main/java/com/onetool/server/api/member/business/MemberLoginBusiness.java
  server/src/main/java/com/onetool/server/api/member/controller/MemberController.java
  server/src/main/java/com/onetool/server/api/member/controller/MemberEmailController.java
  server/src/main/java/com/onetool/server/api/member/controller/MemberLoginController.java
  server/src/main/java/com/onetool/server/api/member/domain/Member.java
  server/src/main/java/com/onetool/server/api/member/dto/LoginMember.java
  server/src/main/java/com/onetool/server/api/member/dto/MemberInfoResponse.java
  server/src/main/java/com/onetool/server/api/member/dto/MemberSimpleInfoDto.java
  server/src/main/java/com/onetool/server/api/member/dto/MemberUpdateRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/command/MemberCreateCommand.java
  server/src/main/java/com/onetool/server/api/member/dto/command/MemberUpdateCommand.java
  server/src/main/java/com/onetool/server/api/member/dto/request/LoginRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/request/MemberCreateRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/request/MemberFindEmailRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/request/MemberFindPwdRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/request/MemberUpdateRequest.java
  server/src/main/java/com/onetool/server/api/member/dto/response/BlueprintDownloadResponse.java
  server/src/main/java/com/onetool/server/api/member/dto/response/MemberCreateResponse.java
  server/src/main/java/com/onetool/server/api/member/dto/response/MemberInfoResponse.java
  server/src/main/java/com/onetool/server/api/member/dto/response/MemberLoginResponse.java
  server/src/main/java/com/onetool/server/api/member/repository/MemberJpaRepository.java
  server/src/main/java/com/onetool/server/api/member/repository/MemberRepository.java
  server/src/main/java/com/onetool/server/api/member/service/MemberService.java
  server/src/main/java/com/onetool/server/api/order/Orders.java
  server/src/main/java/com/onetool/server/api/qna/business/QnaBoardBusiness.java
  server/src/main/java/com/onetool/server/data/DataLoader.java
  server/src/main/java/com/onetool/server/data/DummyDataLoader.java
  server/src/main/java/com/onetool/server/data/TestDataLoader.java
  server/src/main/java/com/onetool/server/global/auth/login/handler/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/onetool/server/global/auth/login/service/CustomOAuth2UserService.java
  server/src/main/java/com/onetool/server/global/auth/login/service/CustomUserDetailsService.java
  server/src/test/java/com/onetool/server/api/member/business/MemberBusinessTest.java
  server/src/test/java/com/onetool/server/api/member/controller/MemberControllerTest.java
  server/src/test/java/com/onetool/server/api/member/fake/FakeMemberJpaRepository.java
  server/src/test/java/com/onetool/server/api/member/fixture/MemberFixture.java
  server/src/test/java/com/onetool/server/api/member/service/MemberServiceTest.java
  server/src/test/java/com/onetool/server/api/qna/business/QnaBoardBusinessTest.java
  server/src/test/java/com/onetool/server/api/qna/controller/QnaBoardControllerTest.java
  server/src/test/java/com/onetool/server/member/MemberServiceTest.java
Labels: ♻️ refactor
