Repository likelion-onetool/backend, pull requests merged in 2025-01, with the labels that each got.

#112 feat: blueprint categoryId 별로 정렬 기능 추가
  server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java
  server/src/main/java/com/onetool/server/api/blueprint/dto/BlueprintSortRequest.java
  server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
Labels: ✨ feat

#115 refactor: 컬렉션 Fatch Join 쿼리 분리를 통한 N+1 해결
  server/src/main/java/com/onetool/server/DataLoader.java
  server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
  server/src/main/resources/application.properties
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
Labels: ♻️ refactor

#116 fix: BlueprintService의 @Trasaction self-invocation 문제 해결
  server/src/main/java/com/onetool/server/api/blueprint/controller/BlueprintController.java
  server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java
  server/src/main/java/com/onetool/server/api/blueprint/repository/BlueprintRepository.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintService.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceTest.java
  server/src/test/java/com/onetool/server/category/CategoryServiceTest.java
Labels: 🛠 fix, 🐛bug

#118 refactor: BlueprintSearchService에 읽기 전용 트랜잭션 부여
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
Labels: ♻️ refactor

#120 fix: 로그인, RefreshToken 재발급 토큰 전달 방식 수정
  server/src/main/java/com/onetool/server/api/member/controller/MemberController.java
  server/src/main/java/com/onetool/server/global/redis/controller/TokenController.java
Labels: 🛠 fix

#128 fix: RefreshToken 인증 버그 해결
  server/src/main/java/com/onetool/server/global/auth/AuthService.java
Labels: 🛠 fix, 🔥 emergency

#129 refator: CategoryName별로 정렬 기능
  server/src/main/java/com/onetool/server/api/blueprint/controller/SearchController.java
  server/src/main/java/com/onetool/server/api/blueprint/dto/BlueprintSortRequest.java
  server/src/main/java/com/onetool/server/api/blueprint/service/BlueprintSearchService.java
  server/src/main/java/com/onetool/server/api/category/FirstCategoryType.java
  server/src/main/java/com/onetool/server/global/exception/CategoryNotFoundException.java
  server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/test/java/com/onetool/server/blueprint/BlueprintServiceMockTest.java
Labels: ♻️ refactor

#132 feat(toss): 결제승인 API
  server/build.gradle
  server/src/main/java/com/onetool/server/api/payments/controller/PaymentController.java
  server/src/main/java/com/onetool/server/api/payments/domain/PaymentProperties.java
  server/src/main/java/com/onetool/server/api/payments/domain/TossPayment.java
  server/src/main/java/com/onetool/server/api/payments/domain/TossPaymentMethod.java
  server/src/main/java/com/onetool/server/api/payments/domain/TossPaymentStatus.java
  server/src/main/java/com/onetool/server/api/payments/dto/PaymentErrorResponse.java
  server/src/main/java/com/onetool/server/api/payments/dto/SaveAmountRequest.java
  server/src/main/java/com/onetool/server/api/payments/repository/PaymentRepository.java
  server/src/main/java/com/onetool/server/api/payments/service/PaymentService.java
  server/src/main/java/com/onetool/server/global/config/SecurityConfig.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/main/resources/application.properties
Labels: ✨ feat, 🔥 emergency

#133 fix: SearchResponse 수정
  server/src/main/java/com/onetool/server/api/blueprint/dto/SearchResponse.java
  server/src/main/java/com/onetool/server/api/cart/controller/CartController.java
Labels: 🛠 fix, 🔥 emergency

#137 fix: 장바구니 읽기, 쓰기, 삭제 버그 수정
  server/src/main/java/com/onetool/server/api/cart/Cart.java
  server/src/main/java/com/onetool/server/api/cart/CartBlueprint.java
  server/src/main/java/com/onetool/server/api/cart/repository/CartRepository.java
  server/src/main/java/com/onetool/server/api/cart/service/CartServiceImpl.java
Labels: 🛠 fix, 🔥 emergency

#140 chore: 데이터 duplicate 문제 해결
  server/src/main/java/com/onetool/server/DataLoader.java
  server/src/main/resources/application-dev.properties
Labels: 🛠 fix

#144 feat: 세션을 이용한 구매 목록 조회, 추가, 삭제
  server/src/main/java/com/onetool/server/api/cart/controller/CartSessionController.java
  server/src/main/java/com/onetool/server/api/cart/dto/CartSessionResponse.java
  server/src/main/java/com/onetool/server/api/cart/service/CartSessionService.java
Labels: ✨ feat, 🔥 emergency

#154 fix(member): ID 기반 작성한 문의사항 조회 수정
  server/src/main/java/com/onetool/server/api/member/controller/MemberController.java
  server/src/main/java/com/onetool/server/api/member/controller/MemberEmailController.java
  server/src/main/java/com/onetool/server/api/member/service/MemberService.java
  server/src/main/java/com/onetool/server/api/qna/dto/response/QnaBoardResponse.java
  server/src/main/java/com/onetool/server/api/qna/repository/QnaBoardRepository.java
Labels: 🛠 fix

#156 fix(email): 인증코드 및 임시 비밀번호 양식 및 발송 이메일 변경
  server/build.gradle
  server/src/main/java/com/onetool/server/api/mail/MailService.java
  server/src/main/java/com/onetool/server/api/member/controller/MemberEmailController.java
  server/src/main/java/com/onetool/server/api/member/service/MemberService.java
  server/src/main/java/com/onetool/server/global/handler/ExceptionAdvice.java
  server/src/main/resources/templates/authcode.html
  server/src/main/resources/templates/password.html
Labels: 🛠 fix

#161 fix(payment): 결제 생성 시 orderId를 Request로 받도록 수정
  server/src/main/java/com/onetool/server/api/order/controller/OrderController.java
  server/src/main/java/com/onetool/server/api/order/service/OrderServiceImpl.java
  server/src/main/java/com/onetool/server/api/payments/dto/DepositRequest.java
  server/src/main/java/com/onetool/server/api/payments/service/DepositService.java
Labels: 🛠 fix

#162 fix(payment, order): 예외 처리
  server/src/main/java/com/onetool/server/api/order/controller/OrderController.java
  server/src/main/java/com/onetool/server/api/order/dto/request/OrderRequest.java
  server/src/main/java/com/onetool/server/api/payments/dto/DepositResponse.java
  server/src/main/java/com/onetool/server/api/payments/service/DepositService.java
  server/src/main/java/com/onetool/server/global/exception/codes/ErrorCode.java
Labels: 🛠 fix
